# Form implementation generated from reading ui file 'D:\HK7\ML\K234161840_NguyenThuyMyLinh\tuan5\retail_project\uis\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 293)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 40, 211, 191))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 14))
        self.label.setObjectName("label")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setGeometry(QtCore.QRect(20, 40, 171, 20))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Password = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_Password.setGeometry(QtCore.QRect(20, 90, 171, 20))
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 120, 131, 18))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_Login = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_Login.setGeometry(QtCore.QRect(20, 150, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\HK7\\ML\\K234161840_NguyenThuyMyLinh\\tuan5\\retail_project\\uis\\../images/ic_login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Login.setIcon(icon)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.pushButton_Exit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_Exit.setGeometry(QtCore.QRect(120, 150, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\HK7\\ML\\K234161840_NguyenThuyMyLinh\\tuan5\\retail_project\\uis\\../images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Exit.setIcon(icon1)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 121, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\HK7\\ML\\K234161840_NguyenThuyMyLinh\\tuan5\\retail_project\\uis\\../images/ic_login_screen.png"))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_Exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Login System:"))
        self.label.setText(_translate("MainWindow", "Email:"))
        self.lineEditEmail.setText(_translate("MainWindow", "obama@gmail.com"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.lineEdit_Password.setText(_translate("MainWindow", "123"))
        self.checkBox.setText(_translate("MainWindow", "Save login information"))
        self.pushButton_Login.setText(_translate("MainWindow", "Login"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
